name: modemate
author: tussat
version: '1.0'
main: com.labi.main.Modemate
api-version: '1.20'

permissions:
  server.op:
    description: Allows the player to switch between enable and disable
    default: op

commands:
    mplugin:
        description: Main command
        usage: /<command> <enable/disable>
    mworld:
      description: World commands
      usage: /mworld <args>
