name: modemate
author: tussat
version: '1.0'
main: com.labi.main.Modemate
api-version: '1.20'

permissions:
  server.op:
    description: Allows the player to switch between enable and disable
    default: op

commands:
    mplugin:
        description: Main command
        usage: /mplugin <args>
    mtime:
      description: Allows the player to manipulate the world time
      usage: /mtime <args>
